import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import internal from "stream";
import styles from "../styles/Home.module.css";

interface Player {
  name: string;
  rank: number;
  rating: number;
  winRate: string;
  games: number;
  lastGame: string;
}

const PlayerInfo: Player[] = [
  {
    name: "Liquid.DeMuslim",
    rank: 1,
    rating: 2069,
    winRate: "85%",
    games: 244,
    lastGame: "1 Day ago",
  },
  {
    name: "BeastyQT",
    rank: 1,
    rating: 2069,
    winRate: "85%",
    games: 244,
    lastGame: "1 Day ago",
  },
];

console.log(PlayerInfo);

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Age Of Empires IV</h1>
        <div className="top-list">
          <h2>Top 10 ranked</h2>
          <div className="flex">
            <div className="player">
              <div className="rank">#1</div>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
